version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: cvehub-mongodb
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cvehub-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: cvehub-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=cvehub
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - cvehub-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cvehub-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - WDS_SOCKET_PORT=0
    depends_on:
      - backend
    networks:
      - cvehub-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  cvehub-network:
    driver: bridge
