version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: cvehub-mongodb
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    networks:
      - cvehub-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh 10.0.7.200:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: cvehub-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - ./backend/.env:/app/.env
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/cvehub
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - cvehub-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cvehub-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=${SERVER_HOST:-http://10.0.7.200:8000}
      - REACT_APP_WS_URL=${SERVER_WS_HOST:-ws://10.0.7.200:8000}
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - cvehub-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  cvehub-network:
    driver: bridge
